#!/bin/bash
set -e
if [ "$1" = "purge" ]; then
    rm -f /boot/overlay-user/max98357a.dtbo
    if [ -f /boot/armbianEnv.txt ]; then
        sed -i -E 's/(^user_overlays=.*)\bmax98357a\b ?/\1/' /boot/armbianEnv.txt || true
        sed -i -E '/^user_overlays=[[:space:]]*$/d' /boot/armbianEnv.txt || true
    fi
    systemctl daemon-reload >/dev/null 2>&1 || true
fi
exit 0
